### ISSUE TITLE
F-Droid: Disappeared

### ISSUE THREAD

**Issue by erebion** [programmin1/Repeater-START-android#13]
Repeater-START has been removed from F-Droid because of a non-free library. Could you please have a look and maybe get the app back to F-Droid?

**Comment by programmin1** [comment]
This was attempted a few months ago but it was not reaccepted, there are some build issues - https://github.com/programmin1/Repeater-START-android/issues/11

Maybe someone who is a master at build/Gradle can figure this out to exclude non-OSS while still letting it build, something like this non working branch I just tried some changes on: 
https://github.com/programmin1/Repeater-START-android/tree/buildExperimentsSoFdroidMightBuildOneDay

Meanwhile please use https://hearham.com/ and the linked previous working build that was on Fdroid, on the front page.

**Comment by programmin1** [comment]
It seems they wouldn't accept the modified build...

Good news is this was accepted on Google Play, with some additional extra premium features for purchase, GMRS support and more - https://play.google.com/store/apps/details?id=com.hearham.repeaterstartpremium

Please support the project by getting it there.

**Comment by erebion** [comment]
> Please support the project by getting it there.

I don't use Google stuff. I'd support the project if it was still accessible by me.

**Comment by programmin1** [comment]
> > Please support the project by getting it there.
> 
> I don't use Google stuff. I'd support the project if it was still accessible by me.

The apk of the last Fdroid version is still available here, and linked at the top of hearham.com/repeaters - https://sourceforge.net/projects/repeater-start/

I would like it to be on F-droid but neither F-droid community nor Mapbox gave useful help in building the app with zero Google libraries so it can stay on F-droid. 
In fact, updating from the current several-years-old Mapbox Android library to a recent one will apparently require a non public api key which would further complicate the OSS build.

Furthermore some say F-droid is not so great for security, all apps having no requirements for Android security api minimums, and all being built and signed by the people at F-droid rather than the developer - https://web.archive.org/web/20220319220603/https://wonderfall.dev/fdroid-issues/

**Comment by erebion** [comment]
I know @IzzySoft does a lot of "Getting Apps into F-Droid" and maybe can help..? I saw that person often in similar issues I was following. :)

**Comment by erebion** [comment]
Or maybe @IzzySoft can at least link to some useful ressources or knows somone to talk to. :)

**Comment by IzzySoft** [comment]
> does a lot of "Getting Apps into F-Droid"

Did a lot, yeah. But I'm currently [not active at F-Droid](https://gitlab.com/fdroid/admin/-/issues/447). Now I mainly concentrate on doing a lot "Getting Apps into IzzyOnDroid" and improve that place – which I started back in 2016.

Wonderfall: that study misses several points. It's often pointed to as being from some security expert, but the security expertise of the author was never found. It's rather a personal stance from someone. It has some valid points, though, but the overall impression is rather a bit misleading.

Now, let me have a look for what you asked for: Hm, "There aren’t any releases here" it says at [releases](https://github.com/programmin1/Repeater-START-android/releases) – so IzzyOnDroid cannot help there. We'd need the APKs, attached to their corresponding tagged releases. Then, the last code change was 2 years ago – is this project still maintained at all? Makes no sense to add it to IoD if it is no longer maintained.

> but neither F-droid community nor Mapbox gave useful help

Ah, Mapbox it is? [My snippet](https://gitlab.com/-/snippets/1896503#alternatives-to-google-maps-api) mentions something on that, like how to disable telemetry – and links to alternatives like maplibre. Might be worth a look.

> require a non public api key which would further complicate the OSS build.

Non-public, eh? Can be extracted from the APK. So there are ways for that (at least with IzzyOnDroid, even with [Reproducible Builds](https://reproducible-builds.org/) – see [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). But the main point here is: Is the app still maintained?
