### ISSUE TITLE
[suggestion] data from repeatermap.de / other sources

### ISSUE THREAD

**Issue by DC7IA** [programmin1/Repeater-START-android#4]
Hey there, just discovered the app on f-droid, definitely something I was really missing there!

Did you consider using some data from repeatermap.de? I think they might agree to that. Covers pretty much all of Europe and people can edit the data.

Also, how do I actually see repeaters around me? When zooming out I see a single IRLP station, but I know there are many more repeaters..? Cannot find any settings. :thinking:

**Comment by DC7IA** [comment]
I wonder why it shows even that single station, since the web version doesn't show a single version in all of Germany.

*single station

**Comment by programmin1** [comment]
The web map? I have not updated that recently, I should.
I asked on the contact form, we'll see. I had not seen that repeatermap for Europe before.

**Comment by programmin1** [comment]
I have just updated the map - https://hearham.com/repeaters/mapbox
I have some DMR repeaters brought in and working - all over Europe there should be more repeaters if you are interested in digital radio:
https://howtotrainyourrobot.com/merry-christmas-and-a-repeater-listing-update/

I have contacted the repeatermap.de developer as well.

**Comment by DC7IA** [comment]
Where did you get the data from? I'm seeing a decommissioned repeater that hasn't been active for years: DB0MES

Just yesterday I talked to the person who owned it years ago because I didn't receive it. Very annoying. :D 
Now I'm trying to get it purged from all databases online.

**Comment by programmin1** [comment]
I've asked radioid support, since those are digital I would think those would be quickly known if they are down :(
