### ISSUE TITLE
[feature request] Support Maidenhead Locators

### ISSUE THREAD

**Issue by DC7IA** [programmin1/Repeater-START-android#5]
While I really like the 3 words system, [Maidenhead Locators](https://en.wikipedia.org/wiki/Maidenhead_Locator_System) are much more common in amateur radio. Maybe this could be added. :)

**Comment by programmin1** [comment]
That's like grid squares? you want to search and go to a specific locator?

**Comment by DC7IA** [comment]
Exactly, that'd be a really brilliant feature to have. :)

Clubstations usually have a small grid square sign somewhere, when doing SOTA the square usually gets looked up and when someone says "My grid is X" radio amateurs usually know roughly where that is.

**Comment by programmin1** [comment]
Okay can you give an example, "my grid is x"?
I would think it is probably a pretty easy calculation too?

**Comment by DC7IA** [comment]
Have a look at the Wikipedia article I have linked to.

The part "Description of the system" explains it much better than I could. :)

**Comment by programmin1** [comment]
I ported a solution .cs and added it - coming in next release. https://github.com/programmin1/Repeater-START-android/commit/15ec70a3471dadb0b5d576593d92ab71b8fa4d03

**Comment by DC7IA** [comment]
Just tested it, brilliant!

**Comment by programmin1** [comment]
I see 0.3 is just up today, glad it works for you.
