### ISSUE TITLE
suggestion: kilometres

### ISSUE THREAD

**Issue by DC7IA** [programmin1/Repeater-START-android#7]
I'd like to suggest either having way to set the distance to kilometres instead of miles or to just display both.

Much of the world has no idea what a mile is. :)

(Only countries that use miles: USA, Liberia, Myanmar, partly in the UK  [ https://www.statista.com/chart/18300/countries-using-the-metric-or-the-imperial-system/ ])

**Comment by programmin1** [comment]
The option is right there in the settings... oh, in the _Linux_ version that is.
If you want that option you'll have to create a settings screen, I don't have time right now.
Hopefully Librem phone will be shipping to us all soon and we don't have to use Android version :)

If you take this on please open a pull request.

**Comment by programmin1** [comment]
You may be pleased to see this is in the fourth revision, just built and available on F-Droid.
There is one option right now, the km/mile option. There may be more in the future.

Thanks for your input and please post if you notice anything else amiss.
