### ISSUE TITLE
A blocked button on the main page

### ISSUE THREAD

**Issue by EasyVector** [programmin1/Repeater-START-android#8]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the main page, **the add button is blocked by its border so I could not know its function in this circumstance unless I shrink the font and display size**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 0.5 my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see the add button fully instead of being blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.open this app for the first time
3.this error could be seen

**Screenshot**

(The blocked part is marked in red)

<img src="https://user-images.githubusercontent.com/25502419/129912333-935fde7d-db94-499f-a5a1-69a32ab43c60.png" alt="copy" width="250"/>

**Environment**

1. Version of Repeater-START : 0.5
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by programmin1** [comment]
That font size is enormous. The repeaters are coming from the database here

https://hearham.com/repeaters/all

and if you click add you can add missing repeaters there:

https://hearham.com/repeaters/add

**Comment by EasyVector** [comment]
Thanks! I did some modifications to avoid such blocking issues and made this page more responsive. I would appreciate it if you could take a look at my pull request. :)

**Comment by programmin1** [comment]
Thank you, included for this update.
